rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3

before_script: "./spec/ci/before_script"

script: "./spec/ci/script"

env:
  - RADIANT_VERSION=1.0.0 DB=mysql
  - RADIANT_VERSION=1.0.0 DB=postgres
  - RADIANT_VERSION=1.1.0.alpha DB=mysql
  - RADIANT_VERSION=1.1.0.alpha DB=postgres

notifications:
  irc: "irc.freenode.org#radiantcms"